// Package rest provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen version v1.13.4 DO NOT EDIT.
package rest

// ServiceUnavailable defines model for ServiceUnavailable.
type ServiceUnavailable struct {
	Code   *string `json:"code,omitempty"`
	Errors *[]struct {
		Code  *string `json:"code,omitempty"`
		Field *string `json:"field,omitempty"`
	} `json:"errors,omitempty"`
	Message *string `json:"message,omitempty"`
	Type    *string `json:"type,omitempty"`
}

// N503ServiceUnavailable defines model for 503_ServiceUnavailable.
type N503ServiceUnavailable = ServiceUnavailable

// NewExpense defines model for NewExpense.
type NewExpense struct {
	Price  *int    `json:"price,omitempty"`
	Title  *string `json:"title,omitempty"`
	UserId *int    `json:"user_id,omitempty"`
}

// PostV1ExpensesJSONBody defines parameters for PostV1Expenses.
type PostV1ExpensesJSONBody struct {
	Price  *int    `json:"price,omitempty"`
	Title  *string `json:"title,omitempty"`
	UserId *int    `json:"user_id,omitempty"`
}

// PostV1ExpensesJSONRequestBody defines body for PostV1Expenses for application/json ContentType.
type PostV1ExpensesJSONRequestBody PostV1ExpensesJSONBody
