// Package rest provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen version v1.13.4 DO NOT EDIT.
package rest

import (
	openapi_types "github.com/deepmap/oapi-codegen/pkg/types"
)

// PostExpensesJSONBody defines parameters for PostExpenses.
type PostExpensesJSONBody struct {
	Amount      *float32            `json:"amount,omitempty"`
	Date        *openapi_types.Date `json:"date,omitempty"`
	Description *string             `json:"description,omitempty"`
}

// PostExpensesJSONRequestBody defines body for PostExpenses for application/json ContentType.
type PostExpensesJSONRequestBody PostExpensesJSONBody
