version: '3.3'

services:
  actions:
    build:
      context: ../
      dockerfile: .github/Dockerfile
    volumes:
      - ../backend:/app

    depends_on:
      - postgres
    environment:
      GITHUB_WORKFLOW: "true"
    env_file:
      - ../.env.dev
    command: sh -c "while true; do sleep 1; done"

  postgres:
    image: postgres:15.2
    ports:
      - 5432:5432
    env_file:
      - ../.env.dev

