// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package graph

import (
	"time"
)

type Expense struct {
	ID        string    `json:"id"`
	Title     string    `json:"title"`
	Price     uint      `json:"price"`
	UserID    uint      `json:"userId"`
	CreatedAt time.Time `json:"createdAt"`
	UpdatedAt time.Time `json:"updatedAt"`
}

type FindUser struct {
	UserID uint `json:"userId"`
}

type NewExpense struct {
	Title  *string `json:"title,omitempty"`
	Price  *uint   `json:"price,omitempty"`
	UserID uint    `json:"userId"`
}

type NewUser struct {
	Name *string `json:"name,omitempty"`
}

type User struct {
	ID        string    `json:"id"`
	Name      string    `json:"name"`
	CreatedAt time.Time `json:"createdAt"`
	UpdatedAt time.Time `json:"updatedAt"`
}
